"""The doubles and the cold harness the gateway scenarios are built over.

What is real is everything the gateway and the SDK own; what is faked is the two
boundaries the SDK injects, the cloud plane and the SIP transport, plus a media
tap. ``Harness`` hands a scenario the doubles and a client built on them, and the
transport is gated so a scenario can hold an INVITE open after the panel streamed,
which is the one window a dialog can end in mid-command. The clock does not move,
so ``at`` is a value a scenario can pin.
"""

from __future__ import annotations

import threading
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

from pydantic import SecretStr
from urmet_sdk import CallHandle, CallState, Doorphone, Settings, UrmetClient, UserProfile
from urmet_sdk.testing import (
    FakeCloud,
    FakeMediaTap,
    FakeSipTransport,
    RegistrationBehavior,
    encrypt_sipdata,
)

# The placeholders the protocol specification publishes: no real installation is
# named here, and a failing assertion still reads like the wire.
EMAIL = "tester@example.com"
CLOUD_PASSWORD = "cloud-pass-4f19"
REALM = "sip.urmet.com"
DOORPHONE_MAC = "00:11:22:33:44:55"
DOORPHONE_NAME = "Front Gate"
SIP_USERNAME = "cfw000000000000"
SIP_PASSWORD = "3f2504e0-4f89-41d3-9a0c-0305e82c3301"

PROFILE = UserProfile(user_id="000000", email=EMAIL, account_hash="00000000")
SIPDATA_PAD = bytes((7 * k + 3) % 256 for k in range(32))
SIPDATA_DOCUMENT: dict[str, Any] = {
    "autogeneratedSipCredentials": {
        "password": SIP_PASSWORD,
        "realm": REALM,
        "type": "TYPE_AUTOGENERATED",
        "username": SIP_USERNAME,
    },
    "currentSipCredentialsType": "TYPE_AUTOGENERATED",
    "existingSipCredentials": {
        "password": "",
        "realm": "",
        "type": "TYPE_EXISTING",
        "username": "",
    },
}

BOOT_TIME = datetime(2026, 1, 1, 12, 0, 0, tzinfo=UTC)
GATE_TIMEOUT_S = 10.0
REGISTER_TIMEOUT_S = 2.0
STREAM_TIMEOUT_S = 2.0
OPEN_TIMEOUT_S = 0.5


def frozen_clock() -> datetime:
    """The clock the scenarios stamp their events with. It does not move."""
    return BOOT_TIME


class GatedCloud(FakeCloud):
    """A ``FakeCloud`` whose login blocks until released, freezing boot at REGISTER.

    Registration crosses the cloud on the worker thread before it ever reaches the
    registrar, so holding ``login`` there is what lets a scenario watch the health
    port answer while the binding does not exist yet.
    """

    def __init__(self, *, gate: threading.Event, **fields: Any) -> None:
        super().__init__(**fields)
        self._gate = gate

    def login(self, email: str, password: SecretStr) -> UserProfile:
        self._gate.wait()
        return super().login(email, password)


class GatedTransport(FakeSipTransport):
    """A ``FakeSipTransport`` whose INVITE can be held after the panel streamed.

    Holding one open freezes a command that has everything it waited for and has
    not returned yet, which is the exact window a dialog can end in.
    """

    def __init__(self, **fields: Any) -> None:
        super().__init__(**fields)
        self.invited: CallHandle | None = None
        self.inviting = threading.Event()
        self._open = threading.Event()
        self._open.set()

    def hold_invite(self) -> None:
        self._open.clear()

    def release_invite(self) -> None:
        self._open.set()

    def end_call(self, call: CallHandle) -> None:
        """Report the far end ending ``call``, the way a BYE reaches the client."""
        self._emit_state(call, CallState.ENDED)
        self.drain()

    def invite(self, door: Doorphone, *, want_video: bool) -> CallHandle:
        call = super().invite(door, want_video=want_video)
        self.invited = call
        self.inviting.set()
        if not self._open.wait(GATE_TIMEOUT_S):
            raise AssertionError("the held INVITE was never released")
        return call


class Harness:
    """The doubles, and a client built on them. Each layer builds its own on top."""

    def __init__(
        self,
        *,
        settings: Settings,
        cloud: FakeCloud,
        transport: GatedTransport,
        tap: FakeMediaTap,
        doorphone: Doorphone,
    ) -> None:
        self.settings = settings
        self.cloud = cloud
        self.transport = transport
        self.tap = tap
        self.doorphone = doorphone
        self.clock = frozen_clock
        self._client: UrmetClient | None = None

    @property
    def client(self) -> UrmetClient:
        """The client under test, built on first use."""
        if self._client is None:
            self._client = self.build_client()
        return self._client

    def build_client(self) -> UrmetClient:
        """A client over the same doubles. The transport reports to the last built."""
        return UrmetClient(self.settings, cloud=self.cloud, transport=self.transport)


def build_harness(
    *,
    registration: RegistrationBehavior = "accept",
    open_acknowledged: bool = True,
    video_ready: bool = True,
    login_gate: threading.Event | None = None,
) -> Harness:
    """Wire one cold graph over the doubles, with the failure a scenario needs armed."""
    settings = Settings(
        _env_file=None,
        email=EMAIL,
        password=CLOUD_PASSWORD,
        cloud_base_url="https://cloud.example.invalid/",
        sip_realm=REALM,
        doorphone_mac=DOORPHONE_MAC,
        doorphone_name=DOORPHONE_NAME,
        register_timeout_s=REGISTER_TIMEOUT_S,
        stream_timeout_s=STREAM_TIMEOUT_S,
        open_timeout_s=OPEN_TIMEOUT_S,
        unregister_timeout_s=REGISTER_TIMEOUT_S,
    )
    sipdata = encrypt_sipdata(SIPDATA_DOCUMENT, SIPDATA_PAD)
    cloud: FakeCloud = (
        GatedCloud(gate=login_gate, profile=PROFILE, sipdata=sipdata, behavior="ok")
        if login_gate is not None
        else FakeCloud(profile=PROFILE, sipdata=sipdata, behavior="ok")
    )
    transport = GatedTransport(
        registration=registration,
        open_acknowledged=open_acknowledged,
        video_ready=video_ready,
        realm=REALM,
    )
    return Harness(
        settings=settings,
        cloud=cloud,
        transport=transport,
        tap=FakeMediaTap(video_ready=video_ready),
        doorphone=Doorphone(mac=DOORPHONE_MAC, name=DOORPHONE_NAME),
    )


HarnessFactory = Callable[..., Harness]
